#!/bin/bash
set -e

echo "$@" >${PBPHERE}/temp.t2t.args

if [ "$#" -eq 1 ]; then
  grammar="${PBPHERE}/$1.ohm"
  rewrite="${PBPHERE}/$1.rwr"
elif [ "$#" -eq 2 ]; then
  grammar="${PBPHERE}/$1.ohm"
  rewrite="${PBPHERE}/$2.rwr"
else
  echo "Usage: $0 base            # uses base.ohm and base.rwr" >&2
  echo "   or: $0 grammar-base rewrite-base" >&2
  exit 1
fi
src=-

# t2tlibd is the lib directory for t2t
t2tlibd="${PBP}/t2td/lib"
# wsupport is support.js in the current working directory
wsupport="${PBPHERE}/support.mjs"

node "${t2tlibd}/rwr.mjs" "${rewrite}" >"${PBPHERE}/temp.rewrite.mjs"

sed -e 's/`/` + "`" + String.raw`/g' <"${grammar}" >"${PBPHERE}/temp.grammar"

echo cat "${t2tlibd}/front.part.js" "${PBPHERE}/temp.grammar" "${t2tlibd}/middle.part.js" "${t2tlibd}/args.part.js" "${wsupport}" "${PBPHERE}/temp.rewrite.mjs" "${t2tlibd}/tail.part.js" >"${PBPHERE}/temp.nanodsl.mjs"

cat "${t2tlibd}/front.part.js" "${PBPHERE}/temp.grammar" "${t2tlibd}/middle.part.js" "${t2tlibd}/args.part.js" "${wsupport}" "${PBPHERE}/temp.rewrite.mjs" "${t2tlibd}/tail.part.js" >"${PBPHERE}/temp.nanodsl.mjs"

node "${PBPHERE}/temp.nanodsl.mjs" "${src}"
